### ISSUE TITLE
怎么转发到另一个群里面= =？

### ISSUE THREAD

**Issue by pinkomeo** [Yinzo/SmartQQBot#100]
大佬你好，现在就是我收到了消息之后
传过来的msg里面是本群的信息

如果我想发信息转发 不知道怎么获得其他群的group_id?

**Comment by Yinzo** [comment]
:D 你可以通过[get_group_info函数](https://github.com/Yinzo/SmartQQBot/blob/master/src/smart_qq_bot/bot.py#L667)查询到某特定群号的群，他的group_id，用作发送消息
