### ISSUE TITLE
返回retcode=103 有没有除通过在 w.qq.com 页面上扫码外的方法解决 这个问题

### ISSUE THREAD

**Issue by ELLIEbleu** [Yinzo/SmartQQBot#102]
在进行扫二维码后 出现返回状态码retcode=103 ,有没有除通过在 w.qq.com 页面上扫码外的方法解决 这个问题

**Comment by Yinzo** [comment]
确认一下是否使用的是本项目master最新的程序？因为这边测试是没问题的
