### ISSUE TITLE
2017年2月10日协议更改后无法登陆 [Fixed]

### ISSUE THREAD

**Issue by Jax-EC** [Yinzo/SmartQQBot#106]
从今天开始 貌似无法登陆了。
扫描二维码后 无响应。

但是webqq 可以登陆。

**Comment by JeffreyFish** [comment]
一样情况，经常扫QRcode之后就显示已失效；或者扫成功，但一直无响应。

**Comment by KennethYeah** [comment]
估计webqq协议又改了吧

**Comment by sjdy521** [comment]
改动可以参考这里：
https://github.com/sjdy521/Mojo-URLMonitor/commit/7d91eec3393519e635996208faff83a4b78d111f#diff-31e063e528e257d9e43ae29e9d71e042

**Comment by Yinzo** [comment]
感谢各位的提醒 ;D
以及  @eastpiger 的 PR和 @sjdy521 的帮助！
现在机器人已恢复，各位可以尝试使用，若仍有问题可发到issue中:D
