### ISSUE TITLE
群聊中会自动回复每一句话，如何控制监控的信息格式？

### ISSUE THREAD

**Issue by Spacebody** [Yinzo/SmartQQBot#110]
加入群聊之后，对群里每一句别人的发言都会回复，请问在哪个文件可以设置监控群聊信息的配置？我想实现 @发言人的功能并且只针对特定格式的发言进行回复

**Comment by Yinzo** [comment]
修改turing_bot.py插件

**Comment by Spacebody** [comment]
能够对那个文件的参数给予一点说明吗，不是很清楚应该修改哪一些

**Comment by Yinzo** [comment]
对于有装饰器的那个函数就是收到消息时会触发的插件函数，修改那个函数的处理逻辑即可，比如用`if`判断下来源群号，或者判断下收到的消息(`msg`对象)的内容是否`@`开头之类的。具体的可以查看readme和对应对象的定义

**Comment by Spacebody** [comment]
好的，谢谢

**Comment by Spacebody** [comment]
msg 在传入函数的时候是否是 string 类型，为什么显示 string index is out of range 但是依旧可以实现我要实现的功能呢？

**Comment by Spacebody** [comment]
另外程序中获得 userid 的代码位于哪里？

**Comment by Yinzo** [comment]
查阅定义： https://github.com/Yinzo/SmartQQBot/blob/master/src/smart_qq_bot/messages.py

**Comment by Spacebody** [comment]
搞定了。谢谢
