### ISSUE TITLE
 Pooling returns unknown re tcode 1202,RUNTIMELOG decode poll res ponse error

### ISSUE THREAD

**Issue by billyyong** [Yinzo/SmartQQBot#115]
[WARNING] Sat, 22 Apr 2017 15:24:50  bot.py line 394: Pooling returns unknown re
tcode 1202
[WARNING] Sat, 22 Apr 2017 15:25:50  bot.py line 367: RUNTIMELOG decode poll res
ponse error.

**Comment by Yinzo** [comment]
确认是否本项目master分支代码

**Comment by winkidney** [comment]
这个warning不影响工作的，可能是API偶发性错误。请详细描述问题：）

**Comment by Yinzo** [comment]
这个问题是不影响正常使用，已默认忽略此 retcode 的提醒
