### ISSUE TITLE
现在接受群消息时，无法获取发送者的QQ号

### ISSUE THREAD

**Issue by MichaelAlexZhang** [Yinzo/SmartQQBot#116]
我把接受到的QQ群消息打印出来：

已经接受到信息，如下：
{"result":[{"poll_type":"group_message","value":{"content":[["font",{"color":"000000","name":"微软雅黑","size":10,"style":[0,0,0]}],"qq"],"from_uin":1480934888,"group_code":1480934888,"msg_id":30347,"msg_type":0,"send_uin":3333354148,"time":1493339717,"to_uin":2402343575}}],"retcode":0}

检索信息属性
内容： qq
群号： 272563665
群名称： QQ挂机测试
发送者群名片： None
发送者名称： 寥天一
发送者QQ号：[WARNING] Fri, 28 Apr 2017 08:35:26  bot.py line 900: search_group_members code unknown: {"ec":1,"em":"no&nbsp;login"}
[ERROR] Fri, 28 Apr 2017 08:35:26  main.py line 78: Exception occurs when checking msg.
Traceback (most recent call last):
  File "D:\QQspider\SmartQQBot\src\smart_qq_bot\main.py", line 66, in main_loop
    msg_list = bot.check_msg()
  File "D:\QQspider\SmartQQBot\src\smart_qq_bot\bot.py", line 401, in check_msg
    print (qqmsg.src_sender_id)
  File "D:\QQspider\SmartQQBot\src\smart_qq_bot\messages.py", line 139, in src_sender_id
    for info in member_list:
TypeError: 'NoneType' object is not iterable

发现是bot.py文件中880行附近
url = "http://qun.qq.com/cgi-bin/qun_mgr/search_group_members"
        data = {
            'bkn':  self.bkn,
            'gc':   str(group_id),
            'st':   0,
            'end':  2000,
            'sort': 0,
        }
        response = self.client.post(url, data=data, refer='http://qun.qq.com/member.html')
        logger.debug("search_group_members response: {}".format(response))
        rsp_json = json.loads(response)
        if rsp_json['ec'] == 0:
            return rsp_json.get('mems')
        else:
            logger.warning("search_group_members code unknown: {}".format(response))
            return None

请求回来的json是{"ec":1,"em":"no&nbsp;login"}，不是正常情况

不知道作者有没有什么办法？

群名片的获取也是异常。

谢谢作者的慷慨开源

**Comment by Yinzo** [comment]
这个问题是qun.qq.com的api变更导致的，暂时还没有找到修复的办法，导致与群信息相关的函数受到了影响。
感谢你提供的详细数据并在issue中报告 :D

**Comment by MichaelAlexZhang** [comment]
从http://qun.qq.com/manage.html这个页面（需要扫码登录之后）进入成员管理的页面：http://qun.qq.com/member.html，分析这个页面加载的过程可以发现，中间请求了"http://qun.qq.com/cgi-bin/qun_mgr/search_group_members"
POST参数也是和bot.py原来的代码（850行附近）一样的，如下：
gc:272563665
st:0
end:20
sort:0
bkn:1100259644

我猜测，这里python程序请求失败的原因应该是cookie不同导致的。能不能写一个方法，保留扫码登录http://qun.qq.com/manage.html的cookie？

**Comment by Yinzo** [comment]
是的，请求确实没有变化。我简单测试了一下，qun.qq.com这边的api需要携带一个cookie，一旦你使用了这个cookie请求成功一次之后，一段时间内都不需要携带cookie也可以请求成功。但是我还没有确定是哪（一）个cookie以及如何获得这个cookie

**Comment by xuefer** [comment]
急需解决这个问题. uin 不是唯一的 实在是没法跟踪/识别用户, 总不能让每个用户又对机器人验证个密码

**Comment by Yinzo** [comment]
@xuefer 这个现在也没办法，除非能找到别的api获取用户的真实qq号，现在官方的smartqq无论是群还是好友都看不到真实qq号了，以前的接口也404了

**Comment by xuefer** [comment]
https://github.com/pandolia/qqbot/issues/124
不知道是否可以参考这个

**Comment by Yinzo** [comment]
@xuefer Nice，我看了一下
> 但当 好友/群/群成员 存在同名现象或名称中含特殊字符时，还是存在无法绑定其实际 QQ 的问题。

应该就是用昵称来作为唯一确认的方法的。。。

**Comment by xuefer** [comment]
感觉是跟您的现有代码效果一样的, 登录qun网页接口搜索群, 逼近您的代码也是匹配之后遇到重复/无法解决

可能就是 qun.qq.com 解决验证的问题

目前我测试的效果是即使刚登录, 接口也是得到 "no login", 函数返回 None

**Comment by pandolia** [comment]
http://qun.qq.com/cgi-bin/qun_mgr/search_group_members 接口已经不能用 webqq 这边的 cookie 了。可以使用 http://qinfo.clt.qq.com/cgi-bin/qun_info/get_group_members_new 代替。可以参考一下：

https://github.com/pandolia/qqbot/blob/master/qqbot/qcontactdb/fetch.py#L140~L144

**Comment by xuefer** [comment]
感谢指导呀. @Yinzo 能看看吗?
另外是否解决了 uin_to_account ?

**Comment by Yinzo** [comment]
非常感谢来自 @pandolia 的帮助，群成员qq号获取已更新 :D 
@xuefer 现在开始尝试解决uin_to_account

**Comment by xuefer** [comment]
效率好高. 不过另一个issue我提到的没 cache 的就是这个 src_sender_id -> search_group_members

**Comment by Yinzo** [comment]
@xuefer uin_to_account现在可用了，还加入了一个account_to_uin函数
