### ISSUE TITLE
意见贴

### ISSUE THREAD

**Issue by xiyanxiyan10** [Yinzo/SmartQQBot#12]
- 建议配置相关命令全部沿用   !(行为)  (参数)  (参数)   的格式
 - 是否准许用户调教可以做个开关从command_handler配置
 - 组消息和私聊消息处理可以做成两个函数，在一起代码相对凌乱
 - 机器人学习相关的储存是否可改用pickle库存入文件
 - 工程尽量模块化后可以分发任务一起搞

**Comment by Yinzo** [comment]
+ 第一点指的是依然沿用旧的命令输入模式来修改机器人配置吗？这个可以实现
+ 这个细化配置内容，会加入。
+ 好
+ 第一次了解pickle库，感觉很方便，我之前还准备使用数据库进行存储，不知pickle库与数据库性能上是否有较大差距。
+ 工程模块化这个没问题，之前的开发的确没有太注意到模块化的问题。

**Comment by xiyanxiyan10** [comment]
- 嗯，命令统一格式比较好用
 - 好的
 - 赞
 - 我也没深入研究过，主要是比数据方便，基于文件格式化存放
 - 嗯嗯
