### ISSUE TITLE
{"errmsg":"error","retcode":103} [WARNING] Thu, 11 May 2017 12:36:07  bot.py line 480: Pooling received retcode: 103

### ISSUE THREAD

**Issue by zhmc** [Yinzo/SmartQQBot#124]
现在程序运行一段时间（约三个小时）后，就会发生如下错误，每秒约10条，同时无法正常接收信息，：

{"errmsg":"error","retcode":103}
[WARNING] Thu, 11 May 2017 12:36:07  bot.py line 480: Pooling received retcode:
103

已经接受到信息，如下：
{"errmsg":"error","retcode":103}
[WARNING] Thu, 11 May 2017 12:36:07  bot.py line 480: Pooling received retcode:
103

已经接受到信息，如下：
{"errmsg":"error","retcode":103}
[WARNING] Thu, 11 May 2017 12:36:07  bot.py line 480: Pooling received retcode:
103

已经接受到信息，如下：
{"errmsg":"error!!!","retcode":103}

[WARNING] Thu, 11 May 2017 12:36:08  bot.py line 480: Pooling received retcode:
103

已经接受到信息，如下：
{"errmsg":"error","retcode":103}
[WARNING] Thu, 11 May 2017 12:36:08  bot.py line 480: Pooling received retcode:
103

把进程杀了，重新运行又是正常的了。但过段时间还是会这样

**Comment by Yinzo** [comment]
重新登陆依然反复出现这种情况吗？

**Comment by BuddhaZhang** [comment]
把进程杀了，重新运行又是正常的了。但过段时间还是会这样

**Comment by Yinzo** [comment]
我这边由于没有能够复现你这个情况，你可以尝试在 `bot.py` 的 418 行，改为

```python 
        if ret_code in (0, 116, 1202, 103):
```
这样看看。
注意一下是否会出现收不到消息的情况

**Comment by zhmc** [comment]
现在获取群消息QQ号好像有点问题

发自我的 iPhone

**Comment by Yinzo** [comment]
@zhmc 感谢提醒，已检查，是接口协议更新，master已修复
