### ISSUE TITLE
Cookies login fail, response decode error too many times 有何意义?

### ISSUE THREAD

**Issue by xuefer** [Yinzo/SmartQQBot#125]
请问反复循环 json.loads 有何意义, ValueError 失败的多试几次会成功吗? 不重新请求的话

**Comment by winkidney** [comment]
：）WebUI上提供了二维码，如果有WebUI，则可以去那里重新扫码登录，重试没有作用，只是没有退出进程 @Yinzo 不知道我理解的对不对

**Comment by Yinzo** [comment]
看了一下代码，重试那里有个小bug，只重复了parse没有重复请求。。

**Comment by xuefer** [comment]
嗯, 那我理解就没错了, 有两处是这样吧
我在重写, retry/json 的处理直接做一个函数里了

好多奇葩问题, 官网已经不能用了, 你们可以吗? 我打开好友是空白, 没机会发好友

别人发 < > 收到的是 \u026lt;\u026gt; json 解码后得到  &lt; &gt;
问题是别人发 &lt; &gt; 也一样, 无法区分

另外发送消息的时候我尝试把内容放在font后面, 就得到错误响应 发布出去

**Comment by Yinzo** [comment]
同样用不了。webqq这上面的坑多到不想看它

**Comment by xuefer** [comment]
我也不想看了, 有别的接口吗?
btw, qq xuefer@gmail.com

**Comment by toontong** [comment]
大家都不想看，作者也不想看， 是指这个工程要放弃了吗？    代码有bug也不更新了，是因tx随时禁协议？

**Comment by Yinzo** [comment]
@toontong 保持基本维护
