### ISSUE TITLE
将QQ部分分离出来

### ISSUE THREAD

**Issue by zhongjingjogy** [Yinzo/SmartQQBot#13]
尝试看了一下代码，有点难理解。想请问一下能不能将QQ部分抽象出来，只提供收发消息的接口。对http方面的内容不是很懂，个人改起来无从下手，高手能不能指导一下。我看到github上另外一些人也用了smartqq，还做能把其他一些机器人api的接进来。还有pyaiml这个项目也能做一些聊天机器人的活。要是能够把代码优化一下，把接发消息的接口完善一下，那样和其他模块结合会方便很多。

**Comment by Yinzo** [comment]
最近事情比较多，之后会对代码进行大规模模块化重构。

**Comment by zhongjingjogy** [comment]
nice，非常期待！
