### ISSUE TITLE
登录后，是不能主动发消息吗？只能被动？

### ISSUE THREAD

**Issue by toontong** [Yinzo/SmartQQBot#131]
如题，是不能主动发消息吗？只能被动？？
作者放弃更新工程了吗？  
希望给几个例子：
1.   初始化 QMessage, 主动发消息的。
2.   发送或回复图片的。

**Comment by Yinzo** [comment]
这是一个机器人框架，而不是命令行qq，主要提供的是被动响应。如果需要主动发送消息，请使用 bot.py 中几个发送消息的函数，其中uin可以从接收到的消息中获取，msgid使用随机数即可。另外协议不支持图片

**Comment by toontong** [comment]
ret = bot.send_friend_msg(content=test,
                                       bot.get_self_info()['uin'],
                                       msg_id=randint(1, 10000))
  print ret 
{u'msg': u'send ok', u'errCode': 0}
