### ISSUE TITLE
能否支持@群成员以及接收他人的@

### ISSUE THREAD

**Issue by PillarsZhang** [Yinzo/SmartQQBot#135]
想写一个将多个群之间的传话插件，但是苦于无法发送@，请问有办法实现吗？（另外请问有比较全的API列表吗）
正好在学python，谢谢大佬们成熟的项目～

**Comment by PillarsZhang** [comment]
试过webQQ了，好像是没有@这个功能，但是我想知道QQ里面@之类的特殊消息是用什么代码传输的呢？

**Comment by PillarsZhang** [comment]
后来又研究了一下，酷Q模拟的是安卓国际版APP，支持大部分功能以及提供SDK（当然也有Python的）。但还是要感谢这个项目～

**Comment by Yinzo** [comment]
『@ 用户』的操作确实在 webqq 协议里不被支持，因为官方不支持，所以我们这个项目也不支持 :-)

顺便看到你能自行通过搜索引擎解决问题而感到非常的开心 ;D 

这边暂时没有比较完整的 API 列表， 你可以查看一下 [bot.py 里面 QQBot](https://github.com/Yinzo/SmartQQBot/blob/master/src/smart_qq_bot/bot.py#L99) 这个类下面的函数定义，以及 [messages.py](https://github.com/Yinzo/SmartQQBot/blob/master/src/smart_qq_bot/messages.py) 下面几个类的一些属性和函数定义，这些都是在插件中可以直接调用的 :D

**Comment by PillarsZhang** [comment]
😄 👍
