### ISSUE TITLE
一些功能建议

### ISSUE THREAD

**Issue by darkr4y** [Yinzo/SmartQQBot#15]
1. 希望有可选登陆模式( 二维码 \ 账户密码)
2. 希望有Web界面(Flask或者Tornado完成选择登陆\下线\状态改变\拉取聊天记录Log\输入自定义消息 etc)

因为很多时候部署到LInux都是终端界面,所以查看二维码也不太方便,如果有web直接将二维码输出就方便了.
并且Web可以将Log筛选分类之后入库(SQLite也是可以的),方便信息的查找和功能Debug
如果大体框架稳定了,我可以加入到这个项目来,一起编码
:)

**Comment by Yinzo** [comment]
感谢你的建议。
1. 登录模式在我重构时有想过，所以二维码登陆做成了单独的模块，便于之后添加账号密码登录模式。但是发现账号密码登陆模式由于腾讯方面经常进行登陆协议的修改，导致账号密码方式登陆的维护成本比较高（主要是时间方面），所以暂时还没有下手干的欲望。
2. Web界面有考虑过，主要是用于便捷登陆、日志查询与机器人管理。二维码原本是想直接输出到终端上，但是因为没有现成的库所以搁置了，日志的筛选功能也是有在考虑之中。

但是由于SmartQQ协议的限制，很多应该有的功能都没有办法实现（比如图片收发），而且存在TX协议大改的风险，所以不太建议对这个项目进行深入的开发（痛心）。。。

所以对于这个项目我的开发理念是尽量的易用与精简，避免投入大量成本后被TX坑。如果不怕代码坑掉的话当然无限欢迎加入进来;D

对于这个框架已经暂时没有什么想法了，所以可能不会大改，只是对于插件系统有些不满意。之后可能会补充对于好友类的封装，应该不会对现有框架造成影响。
