### ISSUE TITLE
您好，请问你的IDE是什么？

### ISSUE THREAD

**Issue by pjkui** [Yinzo/SmartQQBot#17]
昨天晚上的时候，我开发了一个群天气查询的功能，发现了一个问题，由于我是python初学者，发现作者您在打印信息的时候，采用的是logging。由于logging输出到一个logging文件中，但是不在终端中显示。但是作者您的readme的提示，是可以随时查看程序输出信息的。所以，我感觉应该是IDE支持的问题，我用的是sublime 3，没有logging的支持。

**Comment by cmzz** [comment]
pycharm控制台也没有输出的

**Comment by hugo-aa** [comment]
你可以你的程序中加入以下代码

```
import logging
logging.basicConfig(level=logging.INFO,  # change to DEBUG to see more info
    filename='./bot.log',
    format="[%(asctime)s][%(levelname)s] %(message)s")
```

然后如果你用Linux就可以用 `tail -f bot.log` 来看输出了

**Comment by cwdtom** [comment]
我这也是对别人做的二次开发，我也用的sublime，直接看的logging文件。本来是群里有人要用，后来他们嫌写数据太烦就没整了。

**Comment by cwdtom** [comment]
感觉直接看logging也没啥问题啊，就是多一个步骤。

**Comment by hugo-aa** [comment]
Sorry 我错解问题了。
你可以把这行去掉就可以让log输出到控制台了
https://github.com/Yinzo/SmartQQBot/blob/f5612264f964479163dc1ff9d2ae6d43f5d2b28c/Group.py#L14

**Comment by pjkui** [comment]
OK， Thanks for reply. 
我以为你们用了独门编辑器呢，所以才问的。因为我开发的平台是windows 没有linux那么强大的命令，所以只能用其他工具来查看输出日志了。

advice:
No.1  关键步骤提示需要print输出。
No.2   感谢开发分享

**Comment by hugo-aa** [comment]
楼主你是Tencent开发团队的吗？是在SmartQQ团队吗？：）
如果是，对这种bot的态度是什么？会尽量block这种机器人，还是持无所谓的态度？

**Comment by pjkui** [comment]
哈哈。。。在我没去腾讯之前。也用C#搞过QQ群机器人，年久失修了都。看到你这个项目，然后就也来凑热闹玩一玩。我不是QQ团队的。对这个我只是做单纯技术尝试，只要不侵害某些公司利益的，还能够为很多群主提供顺心的插件或助手，这是一件令人愉快的事情。如果是滥发广告什么的，影响用户体验的行为，应该不是我们技术人员愿意看到的，也不是腾讯所接受的。

**Comment by hugo-aa** [comment]
👍

**Comment by Yinzo** [comment]
Wow 感谢对这个项目的关注与建议;D
这个机器人原本是直接print在控制台的，后期才改为logging输出到日志文件，所以可能readme上有小部分存在误导，我想我之后会在控制台上print出一些简易的提示来便于理解与使用:D
另外，如果在二次开发上遇到什么问题或者有什么能够提升（使用或开发）体验的建议，也非常欢迎提出来;D
