### ISSUE TITLE
TODO: third party plugin develop support advice

### ISSUE THREAD

**Issue by pjkui** [Yinzo/SmartQQBot#19]
刚刚提交了两个小自己写的第三方功能插件。已经pull request.
开发过程很简单，但是也有一些小建议 ; P

如果我想让天气查询功能，在group，pm，和sess中都能用。需要重复工作三次。每次功能添加 需要修改四个文件。QQRobot_default.conf文件，写明此插件是否使用，然后在`group.py`,`pm.py`以及'sess.py`重复工作三次，写相同的代码才可以。这样的重复工作，我想我们的框架[暂时叫框架]是可以完全避免的。只要用户开发一个第三方类，比如在plugin目录下，然后让用户提供一个run方法，把核心运行代码写在run里面。然后在配置`QQRobot_default.conf`来指定哪儿可以调用这个第三方模块，并提供类名。然后就算是开发完成了。

这样不会让用户修改框架的核心代码，只要专注写好自己的插件就行啦

估计作者最近比较忙，以后有空可以考虑一下这个三方插件的支持，但是不需要着急实现。

**Comment by Yinzo** [comment]
这是首个来自第三方的插件，非常感谢;D 

非常感谢你的这个插件思路，我会认真考虑的:D 现在的这个流程的确比较繁琐，外部插件模块我想是比较有必要的：）

**Comment by Yinzo** [comment]
新框架已实现这一特性:)
