### ISSUE TITLE
can't publish group message

### ISSUE THREAD

**Issue by freefallzhou** [Yinzo/SmartQQBot#20]
the log shows the return code is 0, and everything seems ok, but the group messages are not actually published.

I meet this trouble when deploy code on linux server.

**Comment by Yinzo** [comment]
That phenomenon probably means your account has been 'PROTECT'ed by Tencent.
This problem may cause by such behaviors:

+ Your recent replies contain **URLs, restriction words, totally identical replies in short time**.
+ Your account is **recently register**, or **log in from different geographical position short time**.
+ And some unclear reasons

If you active the bot with another account but this problem still exist, please contact me ;D
