### ISSUE TITLE
Needs operating Group, Pm and Sess at the same time

### ISSUE THREAD

**Issue by john123951** [Yinzo/SmartQQBot#24]
#### 希望 MsgHandler层能提供插件支持
我在谁是卧底模块开发时遇到一个问题，我需要在一场游戏中同时操作Group、Pm以及Sess三个类。
比如我希望用户可以在游戏过程中 发送临时消息给机器人，以得到本局的游戏词信息，这就需要同时向Group和Sess中值入模块代码，且保证是同一个游戏实例。
采用目前的架构不太好实现，迫切希望重构部分代码，以提供支持。

**Comment by Yinzo** [comment]
如果用户发送消息给机器人，来要求返回某个群中的某局游戏的内容，是否有些难以判断用户所在游戏是哪一局？我想如果需要达到既能智能判断用户在哪一局游戏中，且不影响其他插件的正常使用，可能需要做比较大的修改

**Comment by Yinzo** [comment]
新框架已支持这一特性
