### ISSUE TITLE
关于二次开发的建议

### ISSUE THREAD

**Issue by kissthink** [Yinzo/SmartQQBot#29]
#建议1：
能否把接口合并起来？比如我在群聊里面开发了一个网络接口，但是只能在群聊里面使用，而不能在私聊里面，能否合并为一种实现即可？

目前是需要3个文件都实现才行
群聊功能：Group.py
私聊功能：Pm.py
临时对话功能：Sess.py

#建议2
能否在接口里面提供接口获取发送者详细信息，比如发送的人真实qq号码，群里面或者本人昵称，群号，群昵称。 

#建议3
关键词拦截处理能否统一，插件代码彻底模块化，比如我写一个插件A，那么里面可以配置拦截信息，不需要修改Group.py文件达到拦截。 

#建议4
能否添加一个批量发送接口，比如需要通知特定几个人，直接在插件里面调用发送私有消息

#建议5
插件开发的时候能否提供个优雅的debug方式？ 还有能否动态加载插件呢？比如我修改了插件文件，然后可以自动重新加载插件，我记得python好像可以实现这个方式，每次执行插件的时候动态加载。程序给个配置正常运行模式，开发模式。开发模式就动态加载插件，正常模式一次性加载完成
比如开发的时候，难免有bug，每次都要重新扫码登入，再调试代码，这个好繁琐

#ps
这些是我开发插件的时候需要的问题和一些想法，由于python好久没有用了，就不直接改造了，以上想法实现可能需要很多时间，但是实现对于插件开发者来说就太好了，另外感谢作者，希望作者越做越好

**Comment by Yinzo** [comment]
非常详细的建议，我会加入TODO里的，等到一有时间就会尽快更新

**Comment by kissthink** [comment]
python里面有没有好的方式，直接输出结构体里面的内容？比如我需要调试输出 qq返回过来的结构体信息pmMsg GroupMsg

**Comment by Yinzo** [comment]
暂时没有，我一般用PyCharm调试
