### ISSUE TITLE
关于无法再通过web登陆的问题

### ISSUE THREAD

**Issue by seedChen** [Yinzo/SmartQQBot#30]
从12月9日开始，发现用这个代码的扫描二维码的方式登陆不了。
通过浏览器上追踪登陆过程，发现了些问题：原来的d.web2.qq.com被改成了d1.web2.qq.com，所以原代码中通过这个url访问的方法都会返回403 forbidden；在修改完相关代码之后，登陆过程又会在访问http://d1.web2.qq.com/channel/login2的时候失败，在日志中查看到返回的是{"errmsg":"","retcode":100001}的信息，而不是原来的登陆成功的响应了，搜索了一下100001是代表下线的意思。可能是webqq有了新的更新之后登陆过程发生了改变。
所以想请问一下您那边方不方便修改一下，或者您那里有没有比较详细的或者更新的webqq的协议文档可以共享一下的呢？

**Comment by kissthink** [comment]
唉。。。又升级了。。。。太悲剧了。。这个只能自己抓包分析

**Comment by Yinzo** [comment]
这个协议的修改是无法避免会经常遇到的，我也只是通过抓包进行分析的第三方开发者，也是没有详细的文档的，而且最近学业紧张可能抽不出时间来维护，我只会在有其他开发者更新新版协议后进行更新。
