### ISSUE TITLE
关于webQQ新登陆协议的一些说明

### ISSUE THREAD

**Issue by Yinzo** [Yinzo/SmartQQBot#32]
抽空抓包看了一下新协议，登陆流程和逻辑似乎没有太大的改动，主要是登陆时的url由`"http://d.web2.qq.com/channel/login2"`变为了`"http://d1.web2.qq.com/channel/login2"`，但是修改后尝试登陆login2的POST时返回retcode100001 。

并且，发现官方的webQQ在扫描完二维码后与发出登陆POST之间多了两个proxy请求，仔细看了一下是在进行cookies跨域，那么我觉得应该是新版本加强了对于请求cookies的要求（以前机器人发出的请求cookies并没有在意跨域的问题）。

而我之前是直接使用xqin封装的HttpClient.py进行请求操作的，我不太熟悉urllib/2/cookielib的相关操作，故我可能会在过一段时间后将机器人内的请求改为使用requests库，便于管理跨域的cookies。

如果这周末我没抽出时间那就至少要等我考完6级才能更新了。。。

**Comment by Aleishus** [comment]
我已近修复了这个问题，但是用的是java。

k.qq.SmartQQ - QQ群消息:from:null,content:直接圆通
18:00:08.228 [main] INFO  com.yiji.hack.tools.HttpUtil - 请求url:http://d1.web2.qq.com/channel/poll2
参数：[r={"clientid":53999199,"ptwebqq":"04b9b6c10f2a1187ee547c47bbfeef75bb281908cf639d86f7809284850bc40e","psessionid":"8368046764001d636f6e6e7365727665725f77656271714031302e3133332e34312e383400001ad00000066b026e040015808a206d0000000a406172314338344a69526d0000002859185d94e66218548d1ecb1a12513c86126b3afb97a3c2955b1070324790733ddb059ab166de6857","key":""},]
18:00:08.229 [main] INFO  com.yiji.hack.tools.HttpUtil - http header:{Origin=http://d1.web2.qq.com, Referer=http://d1.web2.qq.com/proxy.html?v=20151105001&callback=1&id=2}
18:00:16.956 [main] INFO  com.yiji.hack.tools.HttpUtil - http请求http://d1.web2.qq.com/channel/poll2成功，返回状态码为:200
18:00:16.956 [main] DEBUG com.yiji.hack.qq.SmartQQ - 接收到qq消息:{"result":[{"poll_type":"group_message","value":{"content":[["font",{"color":"000000","name":"微软雅黑","size":10,"style":[0,0,0]}],"圆通10块"],"from_uin":1883605850,"group_code":1883605850,"msg_id":2028,"msg_type":0,"send_uin":2799814939,"time":1450087216,"to_uin":820421292}}],"retcode":0}

18:00:16.957 [main] INFO  com.yiji.hack.qq.SmartQQ - QQ群消息:from:null,content:圆通10块
18:00:17.162 [main] INFO  com.yiji.hack.tools.HttpUtil - 请求url:http://d1.web2.qq.com/channel/poll2
参数：[r={"clientid":53999199,"ptwebqq":"04b9b6c10f2a1187ee547c47bbfeef75bb281908cf639d86f7809284850bc40e","psessionid":"8368046764001d636f6e6e7365727665725f77656271714031302e3133332e34312e383400001ad00000066b026e040015808a206d0000000a406172314338344a69526d0000002859185d94e66218548d1ecb1a12513c86126b3afb97a3c2955b1070324790733ddb059ab166de6857","key":""},]
18:00:17.164 [main] INFO  com.yiji.hack.tools.HttpUtil - http header:{Origin=http://d1.web2.qq.com, Referer=http://d1.web2.qq.com/proxy.html?v=20151105001&callback=1&id=2}
18:00:30.781 [main] INFO  com.yiji.hack.tools.HttpUtil - http请求http://d1.web2.qq.com/channel/poll2成功，

**Comment by Yinzo** [comment]
是哪里进行了修改？Cookies? Referer?

**Comment by Aleishus** [comment]
修改 Referer ,post的数据中 clientId 是数字，不是字符串，不加引号

**Comment by Yinzo** [comment]
Referer我改过了不行，clientId也一直都是数字

**Comment by Aleishus** [comment]
clientid 必须是 53999199  你抓包看看你自己程序 post的content-length 和 浏览器的是不是一样。

**Comment by Yinzo** [comment]
clientId改为53999199后成功登录和接受信息了。。。这协议改得有点让人无语，以及没有消息和有消息的retcode都变成0 了

**Comment by gismanli** [comment]
get_friend_uin2，添加了个t参数，添加后返回了100000，导致拿不到account，是不是对Cookie有要求的原呢？

**Comment by Yinzo** [comment]
我不确定get_friend_uin2这个接口官方还存不存在，但是官方的webqq我没见到还有使用这个接口了，可能已废弃。

**Comment by chpiter** [comment]
2天就需要重新登录一次吧

**Comment by Yinzo** [comment]
两天登陆一次是老问题了

**Comment by eastpiger** [comment]
最近手头有需要，注意到了你的这个项目。正好省下力气做分析了

**Comment by eastpiger** [comment]
今晚也是着手处理了新协议的兼容问题。一会pull给你看看。我fork的版本已经在着手转python3了，等转好了我想重新梳理一下你写的框架结构。

再次表达谢意

**Comment by Yinzo** [comment]
也很感谢你的pull！很高兴这个项目能够帮到你:D

**Comment by eastpiger** [comment]
原vfwebqq的获取来源已经无法通过验证了，必须用新加进来的getvfwebqq来换

**Comment by eastpiger** [comment]
免扫码自动登录已经实现，改了这几个地方

cookie换成可以存储的类型，这是状态维持的基础
分离登录和拉二维码的流程。用一次登录来尝试免二维码登录
当前登录的username不能从qrcode验证来获得，要换成查阅当前账号数据

**Comment by eastpiger** [comment]
q512533897详聊
