### ISSUE TITLE
关于谁是卧底部分的两个问题

### ISSUE THREAD

**Issue by ShuangjiaMo** [Yinzo/SmartQQBot#40]
shuishiwodi.py中的ReadyStatus类里面，在用
`playerInfo.name = game.uin2name(msgDto.send_uin)`
获取name的时候，得到的字符串为空

然后AssignRolesStatus类中，
`game.writePrivate(x.uin, u'[%s]谁是卧底，您本局[%s]的词语是：%s' % (x.name,game.gameId, x.word))`
接收到的网页是404 Not Found，发不出私信

请问是什么问题？

**Comment by gismanli** [comment]
1. 临时消息接口早就弃用了吧，没法私聊陌生人了，改为私密消息吧。
2 .而且代码里的QQ群对应的code的也需要取`http://s.web2.qq.com/api/get_group_name_list_mask2`这个接口里的，参数是vfwebqq和计算的hash。

**Comment by ShuangjiaMo** [comment]
thx~终于能用了
