### ISSUE TITLE
建议增加发消息间隔时间，以免被封号

### ISSUE THREAD

**Issue by zeruniverse** [Yinzo/SmartQQBot#5]
服务器上跑了一只小黄鸡，目前QQ已被封。。。

**Comment by Yinzo** [comment]
我之前也有遇到过被封的情况，不过我运行的两个账号只有一个出现了被封的情况，暂时还不清楚封号的具体原因

**Comment by zeruniverse** [comment]
应该就是发的太快了。。。可以限制一下没5S之允许发送一条。。。

我号倒是没被封，表现为能够私聊，但是群聊自己发送的内容只有自己能看到，群里的人都看不到。

两个号都是这种情况

**Comment by Yinzo** [comment]
有可能，我的账号是直接QQ安全中心提示账号不安全然后要短信解封

**Comment by zeruniverse** [comment]
Tue, 14 Apr 2015 01:00:09  QQBot.py[line:373] INFO {"retcode":102,"errmsg":""}

直接被冻结。QQ安全中心没有任何提示

**Comment by zeruniverse** [comment]
临时消息无法回复，只能自动回复已加好友的人。但是临时消息可以收到

**Comment by zeruniverse** [comment]
可能需要看一下回复临时消息的参数对不对。。。

**Comment by Yinzo** [comment]
指的是私聊回复吗？那个临时消息的消息类型和私聊的不一样，还没完全写好

**Comment by zeruniverse** [comment]
嗯，是的，临时消息都回不出去。私聊可以

**Comment by Yinzo** [comment]
嗯好，我加入到TODO里
