### ISSUE TITLE
WARNING:root:No plugin config file found.

### ISSUE THREAD

**Issue by zacard-orc** [Yinzo/SmartQQBot#50]
就clone完第一次会弹验证码，然后第二次就停了，只会显示No plugin config file found.。

这个是不是要先人肉登录一次SMARTQQ，再运行你的程序的啊？

**Comment by Yinzo** [comment]
当前需要前往官方SmartQQ http://w.qq.com/ 登录一次，然后才能用机器人登录成功。另外需要复制plugin.json.example为plugin.json。这是个bug，已经修复

**Comment by zacard-orc** [comment]
好的~，谢谢哈
