### ISSUE TITLE
Python3语言版本

### ISSUE THREAD

**Issue by eastpiger** [Yinzo/SmartQQBot#53]
我这里维护了一个Python3的兼容版本，就当前项目而言，我认为Python3更适合，因为Urllib、Urllib2、Cookie等库合并为一个库，同时不必单独处理Unicode等等改变比较适合我们当前的开发。顺带Python3版本天然解决了Python2版本Ctrl-C无法退出的问题（尽管不知道为什么）

**Comment by vcnovember** [comment]
支持

**Comment by Yinzo** [comment]
我觉得可以考虑同时兼容2和3 :D

**Comment by 4linuxfun** [comment]
支持

**Comment by winkidney** [comment]
私以为2和3都兼容好点

**Comment by eastpiger** [comment]
OK我试一下双兼容。表示其实对这样满不爽的。。。

**Comment by winkidney** [comment]
@eastpiger 可以考虑用requests代替urllib，而不是用自带带刀库，别的地方的兼容可以考虑用six库来解决：）
辛苦了~
