### ISSUE TITLE
获取群信息失败，"retcode":6

### ISSUE THREAD

**Issue by billyyong** [Yinzo/SmartQQBot#58]
在  插件里面用get_group_info_ext2获取群信息，失败，"retcode":6。
得到的群信息为空，不知道是什么原因
插件代码：
from smart_qq_bot.signals import on_all_message

@on_all_message(name="SamplePlugin")
def sample_plugin(msg, bot):
    print bot.get_group_info_ext2(4136146546)
    print bot.get_friend_info(3535848264)

**Comment by eastpiger** [comment]
4136146546这个是什么？

**Comment by billyyong** [comment]
是我的qq中的一个群号码

**Comment by eastpiger** [comment]
`def get_group_info_ext2(self, gcode):
`
整个API接口内是不会明文使用qq号和群号的，此处是群的一个gcode号码

**Comment by billyyong** [comment]
找了几天也没有找到qq群号码对应的gcode？

**Comment by eastpiger** [comment]
gcode和群uid在每次登陆之后都是不一样的。在获取group list(现在这里没有做这一步，我自己的fork做了)会取得gcode uin和群名称的对应关系。但是WebQQ显然很坚持不在前端直接操作群号数据

**Comment by billyyong** [comment]
找不到两者之间的联系

**Comment by billyyong** [comment]
http://s.web2.qq.com/api/get_group_name_list_mask2
从这里获取group_list.

**Comment by billyyong** [comment]
用self._hash_digest("2745921050",self.ptwebqq)得到hash值后，post http://s.web2.qq.com/api/get_group_name_list_mask2，返回'{"retcode":50}'

源码如下：
        hashvalue=self._hash_digest(uin,self.ptwebqq)
        response = self.client.post(
            url,
            {
                'r': '{{"ptwebqq":"{0}","clientid":{1}}}'.format(
                    self.ptwebqq,
                    hashvalue
                )
            }
        )

**Comment by eastpiger** [comment]
https://github.com/eastpiger/SmartQQBot/blob/dev-QQFAQRobot/src/smart_qq_bot/bot.py
参考423行

**Comment by billyyong** [comment]
调用 self._hash_digest时，里面参数应将self._self_info2['uin']改为self.get_self_info2['uin']。
        response = json.loads(self.client.post(
            'http://s.web2.qq.com/api/get_group_name_list_mask2',
            {
                'r': json.dumps(
                    {
                        "vfwebqq": self.vfwebqq,
                        "hash": self._hash_digest(self.get_self_info2['uin'], self.ptwebqq),
                    }
                )
            },
        ))

**Comment by Yinzo** [comment]
已参考 @eastpiger 的代码补充get_group_name_list_mask2函数。
