### ISSUE TITLE
!list_plugin 报错

### ISSUE THREAD

**Issue by netroby** [Yinzo/SmartQQBot#59]
[ERROR] Fri, 29 Apr 2016 08:57:38  handler.py line 123: Error occurs when running task from plugin [PluginManger].
Traceback (most recent call last):
  File "/home/huzhifeng/workspace/netroby/SmartQQBot/src/smart_qq_bot/handler.py", line 119, in run
    task.func(**task.kwargs)
  File "/home/huzhifeng/workspace/netroby/SmartQQBot/src/smart_qq_bot/signals.py", line 15, in wrapper
    return func(*args, **kwargs)
  File "/home/huzhifeng/workspace/netroby/SmartQQBot/src/smart_qq_plugins/manager.py", line 70, in hello_bot
    return bot.reply_msg(msg, result)
  File "/home/huzhifeng/workspace/netroby/SmartQQBot/src/smart_qq_bot/bot.py", line 670, in reply_msg
    return self.send_buddy_msg(tuin=msg.from_uin, reply_content=reply_content, msg_id=msg.msg_id+1)
  File "/home/huzhifeng/workspace/netroby/SmartQQBot/src/smart_qq_bot/bot.py", line 570, in send_buddy_msg
    self.send_buddy_msg(tuin, reply_content, msg_id, fail_times + 1)
  File "/home/huzhifeng/workspace/netroby/SmartQQBot/src/smart_qq_bot/bot.py", line 547, in send_buddy_msg
    fix_content = str(reply_content.replace("\\", "\\\\\\\\").replace("\n", "\\\\n").replace("\t", "\\\\t"))
AttributeError: 'int' object has no attribute 'replace'

**Comment by winkidney** [comment]
多谢，晚些时候核实修复：）

**Comment by winkidney** [comment]
无法复现：）请拉取最新的主分支重试，并把plugin.json发上来看看：）

**Comment by netroby** [comment]
是最新的分支
```
drwxrwxr-x 2 huzhifeng huzhifeng 4096 4月  29 08:50 config/
drwxrwxr-x 2 huzhifeng huzhifeng 4096 4月  29 08:50 cookie/
drwxrwxr-x 2 huzhifeng huzhifeng 4096 4月  29 08:39 plugin_tests/
-rw-rw-r-- 1 huzhifeng huzhifeng  273 4月  29 08:39 run.py
-rw-rw-r-- 1 huzhifeng huzhifeng   62 4月  29 08:56 satoru.json
-rw-rw-r-- 1 huzhifeng huzhifeng  492 4月  29 08:39 setup.py
drwxrwxr-x 2 huzhifeng huzhifeng 4096 4月  29 08:46 SmartBot.egg-info/
drwxrwxr-x 2 huzhifeng huzhifeng 4096 4月  29 08:50 smart_qq_bot/
drwxrwxr-x 2 huzhifeng huzhifeng 4096 4月  29 08:50 smart_qq_plugins/
drwxrwxr-x 2 huzhifeng huzhifeng 4096 4月  29 08:39 tests/

```

没有找到什么plugin.json

```
⋊> ~/w/n/S/src on master ◦ cd smart_qq_plugins/                         10:13:05
⋊> ~/w/n/S/s/smart_qq_plugins on master ◦ ll                            10:13:51
total 44K
-rw-rw-r-- 1 huzhifeng huzhifeng 1.4K 4月  29 08:39 basic.py
-rw-rw-r-- 1 huzhifeng huzhifeng   16 4月  29 08:39 __init__.py
-rw-rw-r-- 1 huzhifeng huzhifeng  164 4月  29 08:50 __init__.pyc
-rw-rw-r-- 1 huzhifeng huzhifeng 1.9K 4月  29 08:39 manager.py
-rw-rw-r-- 1 huzhifeng huzhifeng 2.7K 4月  29 08:50 manager.pyc
-rw-rw-r-- 1 huzhifeng huzhifeng 2.2K 4月  29 08:39 satoru.py
-rw-rw-r-- 1 huzhifeng huzhifeng 3.9K 4月  29 08:50 satoru.pyc
-rw-rw-r-- 1 huzhifeng huzhifeng 5.1K 4月  29 08:39 tucao.py
-rw-rw-r-- 1 huzhifeng huzhifeng  769 4月  29 08:39 turing_robot.py
-rw-rw-r-- 1 huzhifeng huzhifeng 1.9K 4月  29 08:39 weather.py

```

**Comment by winkidney** [comment]
config/plugin.json
无法复现你的问题：），你自己添加过什么插件之类的东西吗？

**Comment by netroby** [comment]
没添加什么
```
⋊> ~/w/n/S/src on master ◦ cat config/plugin.json                       10:25:17
{
  "plugin_packages": [],
  "plugin_on": [
      "manager",
      "satoru"
  ]
}
```

**Comment by Yinzo** [comment]
非常奇怪是什么导致了plugin manager 回复了一个纯数字内容
