### ISSUE TITLE
如何写一个RPC服务？

### ISSUE THREAD

**Issue by netroby** [Yinzo/SmartQQBot#60]
我想开发一个 自定义的QQ服务。比如利用机器人，跟我们公司的OA集成。oa更新了什么公告，我想通过QQ机器人在群里发一个公告：

如：5.1 公司为大家提供了100元家乐福购物卡，请各部门同事来领取，领取时间4-27 至4-29

所以我想写个RPC插件，但是没有弄懂怎么写

转发消息到web，我可以调用on_all_message, 那么我要发送消息呢？

请指教，我怎么做比较好

**Comment by Yinzo** [comment]
你可以参考basic.py插件，里面只有十几行的代码，非常易读:D 如果有问题可以继续询问

**Comment by winkidney** [comment]
这个不属于Issue，开新的Issue之前请参考Developers Guide，Issue主要用来汇报Bug，或者是新Feature， enhance, etc.
@Yinzo 这种内容是否考虑做一个讨论的地方，而不是在Issue里面做？

**Comment by Yinzo** [comment]
等晚点我开个qq群吧，或者tg群也可以？感觉qq对大部分人方便些

**Comment by Yinzo** [comment]
欢迎加入SmartQQBot交流QQ群，群号473413233 ;D
