### ISSUE TITLE
retcode 100000？

### ISSUE THREAD

**Issue by zacard-orc** [Yinzo/SmartQQBot#61]
retcode 100000？是不是COOKIE校验不通过啊，
我看了下机器人的COOKIE和浏览器还不一样，是不是有JS再启用加了什么东西？目前项目中一些接口都没有调用，我重新启用了这些接口都报1000000

**Comment by eastpiger** [comment]
每次登陆cookie都会不同。删除/src/cookie/cookie.data

**Comment by zacard-orc** [comment]
解决了，原因很复杂。码主关键的功能80%还没实现。。。

**Comment by winkidney** [comment]
@zacard-orc 欢迎PR，让项目变得更好：）

**Comment by zacard-orc** [comment]
直接对Master PR？你要不再New一个Branch比方说Master_Dev，我PR那个吧，改的比较乱，有自己公司的需求还有第三方服务，所以你New一个Branch吧

**Comment by winkidney** [comment]
@zacard-orc 有时间的话，可以专门做一个PR的Branch吗？把代码清洗一下之类，或者剔除一下对于非项目文件的修改？

或者给个项目链接，这边来处理代码？
