### ISSUE TITLE
How should i get the group_uin when I start this program?

### ISSUE THREAD

**Issue by taidongzhe** [Yinzo/SmartQQBot#62]
rt

**Comment by Yinzo** [comment]
在接收的群消息中含有对应群的uin，或者你可以主动调用bot的get_group_name_list_mask2函数获得你的群的uin。另外关于使用上的讨论请使用讨论群473413233讨论

**Comment by KennethYeah** [comment]
我想问一下这个uin会不会变？什么情况下回变？
是不是像群号一样 或者qq号一样，一个群或者一个qq号对应的uin是固定的。
如果uin会变，我怎样主动查询特定QQ好友的uin？是否能通过QQ号查询到uin

**Comment by Yinzo** [comment]
+ uin是会变化的，一般是一段时间之后重新登录就会获取到新的uin，所以不推荐对uin做持久储存
+ 现在可以通过直接读取msg对象(message.py)中的属性或函数，直接得到消息发送者的QQ号或者所在的群号。如果你需要主动获取特定好友的uin的话，bot.py中有get_online_friends_list()函数可以获得好友的uin的，也有uin_to_account可以通过uin查询好友的真实QQ号。 

以上内容如果需要详细了解请直接查看message.py和bot.py
