### ISSUE TITLE
增加plugin_init的装饰器

### ISSUE THREAD

**Issue by winkidney** [Yinzo/SmartQQBot#68]
在登录完成之后，载入插件的时候，会执行这个插件里面的初始化代码。
这个的必要性主要是传入一个已经初始化好的bot对象，而不用直接用app中导入（难以确定bot的可用性状态）。
是否有必要？

BTW：群里有人提到做爬虫的那个可以借由这个实现（虽然实际上没啥关系……）

**Comment by Yinzo** [comment]
好像暂时还没有那个插件需要用到bot来初始化的，不过增加这一机制我觉得也没问题;D
bot的可用性我觉得或许可以定期调用一下get_online_buddies2，根据返回值来维护一个bot里面的boolean？说不定还能由此解决两三天掉一次线的问题(可能性并不大

不过这个和爬虫好像的确没什么关系吧……

**Comment by winkidney** [comment]
@Yinzo 其实可以直接写在插件模块里面，那种持续运行的东西……我的意思其实是，如果有这个装饰器，那么我们可以确保传入的bot对象是login之后的bot。
和爬虫确实没啥关系，那个基佬的写法阻塞了整个进程，所以卡在了插件载入。

**Comment by Yinzo** [comment]
嗯嗯;D 我觉得增加这个装饰器是可以的，这样或许可以对好友列表或者群列表做一些有趣的动作;D
