### ISSUE TITLE
是否考虑制作一个可以在linux下聊QQ的软件 ？

### ISSUE THREAD

**Issue by linux0ne** [Yinzo/SmartQQBot#74]
我实在是搞不懂，为什么要费这么大的气力做一个机器人的软件，并且这个软件还没有多少用户群体，呵呵。
其实我只是想说，最好能制作一份可以在linux上正常与人沟通的QQ复刻版，可以正常接收文件，发送文字、图片、视频、gif动态图片、语音等等，这样更具实用性。

如果之前一个项目叫：pidgin-lwqq，这个项目就很好，无奈作者转入苹果的工作后，停止了开发。

我等代码能力为零的用户还是非常需要高校的人才来编写这样的实用软件的。
期待神作出现。

**Comment by Yinzo** [comment]
如果您愿意把Android QQ的协议完整逆向出来，相信会有一亿个开发者愿意重启Linux 第三方QQ客户端项目的 :)

**Comment by zhongjingjogy** [comment]
Just for fun.

**Comment by linux0ne** [comment]
@Yinzo 哈哈，O my 天！  那这就不现实了。

话说本项目的基础也是android QQ么？？

如果从网页版的QQ入手是否会容易一些？

**Comment by Yinzo** [comment]
@linux0ne 现在就是webqq协议，和lwqq是一样的，只不过之所以没有你所说的那些功能，是因为现在腾讯阉割掉了它除了普通聊天以外80%的功能。

**Comment by KIDJourney** [comment]
简直了。。。

**Comment by sjdy521** [comment]
@linux0ne 可以看看这个 http://www.zhihu.com/question/27470892 不过代码能力为0的用户估计也不会喜欢玩命令行吧……

**Comment by linux0ne** [comment]
@sjdy521 我在努力的查看这个项目，这个项目很不错！  我的代码能力确实很差，更多的时候我是使用者，呵呵。  我努力去理解文档中的指导吧。

**Comment by linux0ne** [comment]
@KIDJourney   你是在说我么？  那不懂，还不让问么？

**Comment by linux0ne** [comment]
@Yinzo 恩，我大概懂你的意思了。
可能在linux下，需要聊天、传文件两项功能的用户也不少，结合了大家的回复，我觉得@sjdy521介绍的那个项目挺不错的。我在学习中……

同时也继续关注你的项目。

**Comment by cassidydog** [comment]
一边说项目主的项目没有用，一边趾高气扬地让项目主帮你写东西。求您别继续关注项目主的项目了。

**Comment by linux0ne** [comment]
@cassidydog 
你是不识字，还是打小就患有人格败坏症？！ 
1、我几时说本项目没有用了？你用脚趾头想，也不可能说它是没有用的吧！你是不是便秘呀？！ 
2、“趾高气扬地让”——就是再宽容的人，也不能允许你如此的诋毁和诬陷。“期待”是个什么样的词汇和语意，现在连幼儿园的小孩子都知道了，可见你连这个级别的水平都不够！

综上：
1、我很尊重作者的项目与工作，本帖的言辞行末无不如此，我亦在圈子中努力地介绍这个项目。所以你没有资格“求”我不关注本项目，因为你不佩！
2、我无意与你玩文字游戏，你这种扇风点火、指鹿为马、満腹草包的家伙，实在让人瞧不起，即便是你会抄袭别人的函数或注释。业以德为先，汝等聒噪之徒还是先学学作人吧。

**Comment by sjdy521** [comment]
应该是下面这句说的比较狭隘，惹毛了那位 ： 

“我实在是搞不懂，为什么要费这么大的气力做一个机器人的软件，并且这个软件还没有多少用户群体，呵呵”

很少在github这种地方见到这种状况

**Comment by linux0ne** [comment]
@sjdy521 
这是一种“五月渔郎相忆否”的句式……好吧好吧，既然是你说了，我只能虚心接受，虽然我的本意并不是奚落本项目，恰恰是表现出了很高的敬意。
希望“呵呵”一词可以体现出我的诙谐和调皮的玩笑表情。

**Comment by KIDJourney** [comment]
mdzz。。。。

**Comment by linux0ne** [comment]
@KIDJourney nmdzz。。。。
