### ISSUE TITLE
retcode为103

### ISSUE THREAD

**Issue by zhongjingjogy** [Yinzo/SmartQQBot#81]
```
Check error. 请前往http://w.qq.com/ 手动登陆SmartQQ一次.
```
我觉得这个错误是因为本地cookie是存在问题，需要删除cookie并重新扫描二维码登陆的。这个问题的产生原因应该是重复登陆，也就是说用户已经通过smartqq登陆了一次了，在没有下线的情况下又登陆了一次，服务器端就会出现将cookie视为有问题的。但是具体那个会有问题，这个还需要重现一下。

**Comment by Yinzo** [comment]
参考 #38

**Comment by zhongjingjogy** [comment]
是这个问题，我在二次开发的时候删掉了这个，没想到有这样的坑。谢谢！
