### ISSUE TITLE
调试basic插件的时候报错

### ISSUE THREAD

**Issue by jackyxie** [Yinzo/SmartQQBot#88]
在群里面，其他成员发送消息“我是谁”，触发对应的自动回复，报错

![screenshot](https://cloud.githubusercontent.com/assets/3347704/18304378/ae7b67d4-7514-11e6-82f1-4190c7a5b6de.png)

**Comment by Yinzo** [comment]
感谢你的报告，可以尝试将bot.py的#780行改为以下代码吗？应该可以解决问题:D
`        for card_dict in self.group_member_info[group_code].get('cards'):`
如果没问题的话我会update主分支的:D

**Comment by jackyxie** [comment]
修改之后还是报错
  File "SmartQQBot/src/smart_qq_bot/bot.py", line 780, in get_group_member_info
    for card_dict in self.group_member_info[group_code].get('cards'):
TypeError: 'NoneType' object is not iterable

**Comment by jackyxie** [comment]
我看了一下里面的数据，是没有cards这个键值

**Comment by Yinzo** [comment]
忘记不能for None了 XD， 改成`for card_dict in self.group_member_info[group_code].get('cards') or []:`如何:D

**Comment by jackyxie** [comment]
正常了，这种修改方式可以
