### ISSUE TITLE
self.reply() 出现不工作情况

### ISSUE THREAD

**Issue by masahoshiro** [Yinzo/SmartQQBot#9]
修改自最后部分“智障机器人”

    def callout(self, content):

      if ".jita " in content:

            itemName = content[6:].encode("utf-8")

            self.reply(itemName) 

            #在此处正常

            se = urllib.urlopen("http://meowo.me/eve-api.php?name=" + urlencode(itemName))

            rs = se.read()

            se.close()

            re = urllib.urlopen("http://www.ceve-market.org/api/market/region/10000002/type/" + rs + ".json")

            rp = re.read()

            re.close()

            #self.reply(rp)

            #放到这里就不工作了 

            print str(self.gid) + itemName + '  ' + rs + '  ' + rp

            #打印没有错误

            return True

    return False

请问下是什么原因导致的呢 又如何修改呢 （为了修改成想要的功能特意去看了 Python 入门

**Comment by masahoshiro** [comment]
当我把第二个 GET 操作注释掉后 self.reply() 就正常工作了

    def callout(self, content):

      if ".jita " in content:

            itemName = content[6:].encode("utf-8")

            se = urllib.urlopen("http://meowo.me/eve-api.php?name=" + urlencode(itemName))

            rs = se.read()

            se.close()

            #re = urllib.urlopen("http://www.ceve-market.org/api/market/region/10000002/type/" + rs + ".json")

            #rp = re.read()

            #re.close()

            self.reply(rs)

            #It works!

            print str(self.gid) + itemName + '  ' + rs 

            #打印没有错误

            return True

    return False

请问下是什么原因导致的呢 又如何修改呢 （为了修改成想要的功能特意去看了 Python 入门

**Comment by Yinzo** [comment]
简单看了一下，应该是因为返回的类型是json导致的，没办法直接与str类型结合
