### ISSUE TITLE
 能不能看看群文件的相关功能

### ISSUE THREAD

**Issue by zhzblackc** [Yinzo/SmartQQBot#90]
1. 比如我有多个群，能不能实现把一个文件上传到多个群
2. 我看淘宝上买有刷群活跃的软件 ，但他们基本是刷表情，能不能做到按事先编好的话术或文字来直接刷文字等

**Comment by Yinzo** [comment]
1. WebQQ协议不支持文件上传功能
2. 本项目不支持机器人的非正常使用。

**Comment by zhzblackc** [comment]
一个群里面可以不可以多个QQ机器人，如果可以理论上是可以做到两个机器人互相聊天的吧？
