### ISSUE TITLE
缺少tkinter

### ISSUE THREAD

**Issue by moboard** [Yinzo/SmartQQBot#91]
archlinux，py2,py3都有，依赖里的Pillow没有安装上（pip list可以看到没有这个包)，执行python run.py或者phthon2 run.py:

```
raise SystemError('缺少Tkinter模块, 可使用sudo pip install Tkinter尝试安装')
SystemError: 缺少Tkinter模块, 可使用sudo pip install Tkinter尝试安装
```
请问下怎么解决啊

**Comment by winkidney** [comment]
pacman -S python-tk ，可以装上么……一般都在系统的包管理器当中可以安装

**Comment by moboard** [comment]
汗一个，仓库里面有一上叫tk的软件包。把这个安装之后就没的提示缺少tkinter.不过会提示缺少另外一个模块，我慢慢试下。谢谢了哈。
