### ISSUE TITLE
bot.py line 331: RUNTIMELOG decode poll res ponse error

### ISSUE THREAD

**Issue by billyyong** [Yinzo/SmartQQBot#96]
[INFO] Sun, 23 Oct 2016 17:20:20  bot.py line 170: Login by cookie succeed. acco
unt: 2564794432
[WARNING] Sun, 23 Oct 2016 17:20:20  bot.py line 331: RUNTIMELOG decode poll res
ponse error.
[WARNING] Sun, 23 Oct 2016 17:20:20  bot.py line 331: RUNTIMELOG decode poll res
ponse error.

**Comment by winkidney** [comment]
这个issue是webqq 返回502 bad gateway导致的，应该不影响正常的信息读取。
