### ISSUE TITLE
能否加个系统消息？

### ISSUE THREAD

**Issue by ye4241** [Yinzo/SmartQQBot#99]
比如加群，退群之类的系统级别消息的触发。

**Comment by Yinzo** [comment]
这个要看协议支不支持，协议不支持的，官方SmartQQ就不支持，我们用这个协议的自然也没有办法支持。加群，退群提示，协议并不支持。但是你可以通过自己监控群成员列表实现加群退群事件的检测

**Comment by ye4241** [comment]
哈哈，今天也看到了一下Smart QQ的页面的，的确没有看到是系统消息之类的。

**Comment by sjdy521** [comment]
pc端的很多信息都是走http协议的，比如加群申请之类的，可以抓包看下，webqq的登录cookie对这些请求也是有效的

**Comment by ye4241** [comment]
@sjdy521 我也就说，为什么酷Q可以有那么多事件，无奈不是跨平台的。

**Comment by sjdy521** [comment]
你特别需要哪些事件？


发自网易邮箱大师
在2016年11月23日 11:33，ye4241 写道:

@sjdy521 我也就说，为什么酷Q可以有那么多事件，无奈不是跨平台的。

**Comment by winkidney** [comment]
@sjdy521 可以考虑使用小灰的https://github.com/sjdy521/Mojo-Webqq   非常赞 : )
